spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://storagetask-postgres-1:5432/products
    username: postgres
    password: 09031999
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
